export const AuditAction = {
  LISTING_CREATED: "LISTING_CREATED",
  LISTING_STATUS_CHANGED: "LISTING_STATUS_CHANGED",
  LISTING_REJECTED: "LISTING_REJECTED",
  VERIFICATION_STEP_ASSIGNED: "VERIFICATION_STEP_ASSIGNED",
  VERIFICATION_STEP_COMPLETED: "VERIFICATION_STEP_COMPLETED",
  TASK_CREATED: "TASK_CREATED",
  TASK_STATUS_CHANGED: "TASK_STATUS_CHANGED",
  PAYMENT_INITIATED: "PAYMENT_INITIATED",
  PAYMENT_SUCCEEDED: "PAYMENT_SUCCEEDED",
  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
  VERIFICATION_STEP_ACCEPTED: "VERIFICATION_STEP_ACCEPTED",
  VERIFICATION_REVISION_REQUESTED: "VERIFICATION_REVISION_REQUESTED",
  PROFESSIONAL_CREDENTIAL_VERIFIED: "PROFESSIONAL_CREDENTIAL_VERIFIED",
  PROFESSIONAL_CREDENTIAL_REJECTED: "PROFESSIONAL_CREDENTIAL_REJECTED",
  PLATFORM_CONFIG_UPDATED: "PLATFORM_CONFIG_UPDATED",
  PRIVATE_DOCUMENT_READ: "PRIVATE_DOCUMENT_READ",
  PRIVATE_DOCUMENT_READ_DENIED: "PRIVATE_DOCUMENT_READ_DENIED",
} as const;

export type AuditActionType = (typeof AuditAction)[keyof typeof AuditAction];
