export const AuditAction = {
  LISTING_CREATED: "LISTING_CREATED",
  LISTING_STATUS_CHANGED: "LISTING_STATUS_CHANGED",
  LISTING_REJECTED: "LISTING_REJECTED",
  VERIFICATION_STEP_ASSIGNED: "VERIFICATION_STEP_ASSIGNED",
  VERIFICATION_STEP_COMPLETED: "VERIFICATION_STEP_COMPLETED",
  TASK_CREATED: "TASK_CREATED",
  TASK_STATUS_CHANGED: "TASK_STATUS_CHANGED",
  PAYMENT_INITIATED: "PAYMENT_INITIATED",
  PAYMENT_SUCCEEDED: "PAYMENT_SUCCEEDED",
  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
} as const;

export type AuditActionType = (typeof AuditAction)[keyof typeof AuditAction];
