import { defineConfig } from "vitest/config";
import tsconfigPaths from "vite-tsconfig-paths";

export default defineConfig({
  plugins: [tsconfigPaths()],
  esbuild: {
    jsx: "automatic",
  },
  test: {
    environment: "jsdom",
    globals: true,
    setupFiles: ["./src/test/setup.ts"],
    css: false,
    include: ["src/**/*.test.{ts,tsx}"],
    coverage: {
      provider: "v8",

      // Measure the whole tree, not only what the tests happen to import. v8's default reports just
      // the files loaded during the run — 20 of 185 here — which scores 48.06% and would have made
      // this floor a fiction: a new untested file would not lower it, because it would not be in
      // it. Naming src/** instead mirrors backend's collectCoverageFrom, so the two numbers mean
      // the same thing and the honest figure is 4.91%.
      include: ["src/**/*.{ts,tsx}"],
      exclude: [
        "src/**/*.test.{ts,tsx}",
        "src/test/**",
        "src/routeTree.gen.ts", // generated by the TanStack Router plugin
        "src/vite-env.d.ts",
      ],
      reporter: ["text-summary", "json-summary", "lcov"],
      reportsDirectory: "./coverage",

      // The floor, measured on e80e24c across all 185 source files:
      //   statements 4.91% (248/5048)   branches 3.21% (133/4143)
      //   functions  3.82% (69/1803)    lines    4.89% (227/4641)
      //
      // 37 tests over 185 files. Set just under each measured number, as backend does: room for
      // 1152 more uncovered statements, 290 branches, 497 functions, 1034 lines before one trips.
      // Low, but not nothing — deleting the tests that cover ~50 statements already fails this.
      thresholds: {
        statements: 4,
        branches: 3,
        functions: 3,
        lines: 4,
      },
    },
  },
});
