/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingsListingIdRouteImport } from './routes/listings.$listingId'
import { Route as DashboardStaffRouteImport } from './routes/dashboard.staff'
import { Route as DashboardSellerRouteImport } from './routes/dashboard.seller'
import { Route as DashboardProfessionalRouteImport } from './routes/dashboard.professional'
import { Route as DashboardBuyerRouteImport } from './routes/dashboard.buyer'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardStaffIndexRouteImport } from './routes/dashboard.staff.index'
import { Route as DashboardSellerIndexRouteImport } from './routes/dashboard.seller.index'
import { Route as DashboardProfessionalIndexRouteImport } from './routes/dashboard.professional.index'
import { Route as DashboardBuyerIndexRouteImport } from './routes/dashboard.buyer.index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard.admin.index'
import { Route as DashboardStaffWorkflowRouteImport } from './routes/dashboard.staff.workflow'
import { Route as DashboardStaffSubmissionsRouteImport } from './routes/dashboard.staff.submissions'
import { Route as DashboardStaffCredentialsRouteImport } from './routes/dashboard.staff.credentials'
import { Route as DashboardSellerListingsRouteImport } from './routes/dashboard.seller.listings'
import { Route as DashboardSellerDocumentsRouteImport } from './routes/dashboard.seller.documents'
import { Route as DashboardProfessionalTasksRouteImport } from './routes/dashboard.professional.tasks'
import { Route as DashboardProfessionalCredentialsRouteImport } from './routes/dashboard.professional.credentials'
import { Route as DashboardBuyerTransactionsRouteImport } from './routes/dashboard.buyer.transactions'
import { Route as DashboardBuyerServicesRouteImport } from './routes/dashboard.buyer.services'
import { Route as DashboardBuyerListingsRouteImport } from './routes/dashboard.buyer.listings'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard.admin.users'
import { Route as DashboardAdminSettingsRouteImport } from './routes/dashboard.admin.settings'
import { Route as DashboardAdminListingsRouteImport } from './routes/dashboard.admin.listings'
import { Route as DashboardProfessionalTasksTaskIdRouteImport } from './routes/dashboard.professional.tasks.$taskId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsListingIdRoute = ListingsListingIdRouteImport.update({
  id: '/listings/$listingId',
  path: '/listings/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStaffRoute = DashboardStaffRouteImport.update({
  id: '/dashboard/staff',
  path: '/dashboard/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSellerRoute = DashboardSellerRouteImport.update({
  id: '/dashboard/seller',
  path: '/dashboard/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfessionalRoute = DashboardProfessionalRouteImport.update({
  id: '/dashboard/professional',
  path: '/dashboard/professional',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBuyerRoute = DashboardBuyerRouteImport.update({
  id: '/dashboard/buyer',
  path: '/dashboard/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStaffIndexRoute = DashboardStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardStaffRoute,
} as any)
const DashboardSellerIndexRoute = DashboardSellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSellerRoute,
} as any)
const DashboardProfessionalIndexRoute =
  DashboardProfessionalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProfessionalRoute,
  } as any)
const DashboardBuyerIndexRoute = DashboardBuyerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardBuyerRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardStaffWorkflowRoute = DashboardStaffWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => DashboardStaffRoute,
} as any)
const DashboardStaffSubmissionsRoute =
  DashboardStaffSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => DashboardStaffRoute,
  } as any)
const DashboardStaffCredentialsRoute =
  DashboardStaffCredentialsRouteImport.update({
    id: '/credentials',
    path: '/credentials',
    getParentRoute: () => DashboardStaffRoute,
  } as any)
const DashboardSellerListingsRoute = DashboardSellerListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => DashboardSellerRoute,
} as any)
const DashboardSellerDocumentsRoute =
  DashboardSellerDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => DashboardSellerRoute,
  } as any)
const DashboardProfessionalTasksRoute =
  DashboardProfessionalTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => DashboardProfessionalRoute,
  } as any)
const DashboardProfessionalCredentialsRoute =
  DashboardProfessionalCredentialsRouteImport.update({
    id: '/credentials',
    path: '/credentials',
    getParentRoute: () => DashboardProfessionalRoute,
  } as any)
const DashboardBuyerTransactionsRoute =
  DashboardBuyerTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => DashboardBuyerRoute,
  } as any)
const DashboardBuyerServicesRoute = DashboardBuyerServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DashboardBuyerRoute,
} as any)
const DashboardBuyerListingsRoute = DashboardBuyerListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => DashboardBuyerRoute,
} as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminSettingsRoute = DashboardAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminListingsRoute = DashboardAdminListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardProfessionalTasksTaskIdRoute =
  DashboardProfessionalTasksTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => DashboardProfessionalTasksRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/buyer': typeof DashboardBuyerRouteWithChildren
  '/dashboard/professional': typeof DashboardProfessionalRouteWithChildren
  '/dashboard/seller': typeof DashboardSellerRouteWithChildren
  '/dashboard/staff': typeof DashboardStaffRouteWithChildren
  '/listings/$listingId': typeof ListingsListingIdRoute
  '/dashboard/admin/listings': typeof DashboardAdminListingsRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/buyer/listings': typeof DashboardBuyerListingsRoute
  '/dashboard/buyer/services': typeof DashboardBuyerServicesRoute
  '/dashboard/buyer/transactions': typeof DashboardBuyerTransactionsRoute
  '/dashboard/professional/credentials': typeof DashboardProfessionalCredentialsRoute
  '/dashboard/professional/tasks': typeof DashboardProfessionalTasksRouteWithChildren
  '/dashboard/seller/documents': typeof DashboardSellerDocumentsRoute
  '/dashboard/seller/listings': typeof DashboardSellerListingsRoute
  '/dashboard/staff/credentials': typeof DashboardStaffCredentialsRoute
  '/dashboard/staff/submissions': typeof DashboardStaffSubmissionsRoute
  '/dashboard/staff/workflow': typeof DashboardStaffWorkflowRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/buyer/': typeof DashboardBuyerIndexRoute
  '/dashboard/professional/': typeof DashboardProfessionalIndexRoute
  '/dashboard/seller/': typeof DashboardSellerIndexRoute
  '/dashboard/staff/': typeof DashboardStaffIndexRoute
  '/dashboard/professional/tasks/$taskId': typeof DashboardProfessionalTasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/listings/$listingId': typeof ListingsListingIdRoute
  '/dashboard/admin/listings': typeof DashboardAdminListingsRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/buyer/listings': typeof DashboardBuyerListingsRoute
  '/dashboard/buyer/services': typeof DashboardBuyerServicesRoute
  '/dashboard/buyer/transactions': typeof DashboardBuyerTransactionsRoute
  '/dashboard/professional/credentials': typeof DashboardProfessionalCredentialsRoute
  '/dashboard/professional/tasks': typeof DashboardProfessionalTasksRouteWithChildren
  '/dashboard/seller/documents': typeof DashboardSellerDocumentsRoute
  '/dashboard/seller/listings': typeof DashboardSellerListingsRoute
  '/dashboard/staff/credentials': typeof DashboardStaffCredentialsRoute
  '/dashboard/staff/submissions': typeof DashboardStaffSubmissionsRoute
  '/dashboard/staff/workflow': typeof DashboardStaffWorkflowRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/buyer': typeof DashboardBuyerIndexRoute
  '/dashboard/professional': typeof DashboardProfessionalIndexRoute
  '/dashboard/seller': typeof DashboardSellerIndexRoute
  '/dashboard/staff': typeof DashboardStaffIndexRoute
  '/dashboard/professional/tasks/$taskId': typeof DashboardProfessionalTasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/buyer': typeof DashboardBuyerRouteWithChildren
  '/dashboard/professional': typeof DashboardProfessionalRouteWithChildren
  '/dashboard/seller': typeof DashboardSellerRouteWithChildren
  '/dashboard/staff': typeof DashboardStaffRouteWithChildren
  '/listings/$listingId': typeof ListingsListingIdRoute
  '/dashboard/admin/listings': typeof DashboardAdminListingsRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/buyer/listings': typeof DashboardBuyerListingsRoute
  '/dashboard/buyer/services': typeof DashboardBuyerServicesRoute
  '/dashboard/buyer/transactions': typeof DashboardBuyerTransactionsRoute
  '/dashboard/professional/credentials': typeof DashboardProfessionalCredentialsRoute
  '/dashboard/professional/tasks': typeof DashboardProfessionalTasksRouteWithChildren
  '/dashboard/seller/documents': typeof DashboardSellerDocumentsRoute
  '/dashboard/seller/listings': typeof DashboardSellerListingsRoute
  '/dashboard/staff/credentials': typeof DashboardStaffCredentialsRoute
  '/dashboard/staff/submissions': typeof DashboardStaffSubmissionsRoute
  '/dashboard/staff/workflow': typeof DashboardStaffWorkflowRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/buyer/': typeof DashboardBuyerIndexRoute
  '/dashboard/professional/': typeof DashboardProfessionalIndexRoute
  '/dashboard/seller/': typeof DashboardSellerIndexRoute
  '/dashboard/staff/': typeof DashboardStaffIndexRoute
  '/dashboard/professional/tasks/$taskId': typeof DashboardProfessionalTasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard/admin'
    | '/dashboard/buyer'
    | '/dashboard/professional'
    | '/dashboard/seller'
    | '/dashboard/staff'
    | '/listings/$listingId'
    | '/dashboard/admin/listings'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/users'
    | '/dashboard/buyer/listings'
    | '/dashboard/buyer/services'
    | '/dashboard/buyer/transactions'
    | '/dashboard/professional/credentials'
    | '/dashboard/professional/tasks'
    | '/dashboard/seller/documents'
    | '/dashboard/seller/listings'
    | '/dashboard/staff/credentials'
    | '/dashboard/staff/submissions'
    | '/dashboard/staff/workflow'
    | '/dashboard/admin/'
    | '/dashboard/buyer/'
    | '/dashboard/professional/'
    | '/dashboard/seller/'
    | '/dashboard/staff/'
    | '/dashboard/professional/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/listings/$listingId'
    | '/dashboard/admin/listings'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/users'
    | '/dashboard/buyer/listings'
    | '/dashboard/buyer/services'
    | '/dashboard/buyer/transactions'
    | '/dashboard/professional/credentials'
    | '/dashboard/professional/tasks'
    | '/dashboard/seller/documents'
    | '/dashboard/seller/listings'
    | '/dashboard/staff/credentials'
    | '/dashboard/staff/submissions'
    | '/dashboard/staff/workflow'
    | '/dashboard/admin'
    | '/dashboard/buyer'
    | '/dashboard/professional'
    | '/dashboard/seller'
    | '/dashboard/staff'
    | '/dashboard/professional/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/dashboard/admin'
    | '/dashboard/buyer'
    | '/dashboard/professional'
    | '/dashboard/seller'
    | '/dashboard/staff'
    | '/listings/$listingId'
    | '/dashboard/admin/listings'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/users'
    | '/dashboard/buyer/listings'
    | '/dashboard/buyer/services'
    | '/dashboard/buyer/transactions'
    | '/dashboard/professional/credentials'
    | '/dashboard/professional/tasks'
    | '/dashboard/seller/documents'
    | '/dashboard/seller/listings'
    | '/dashboard/staff/credentials'
    | '/dashboard/staff/submissions'
    | '/dashboard/staff/workflow'
    | '/dashboard/admin/'
    | '/dashboard/buyer/'
    | '/dashboard/professional/'
    | '/dashboard/seller/'
    | '/dashboard/staff/'
    | '/dashboard/professional/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardBuyerRoute: typeof DashboardBuyerRouteWithChildren
  DashboardProfessionalRoute: typeof DashboardProfessionalRouteWithChildren
  DashboardSellerRoute: typeof DashboardSellerRouteWithChildren
  DashboardStaffRoute: typeof DashboardStaffRouteWithChildren
  ListingsListingIdRoute: typeof ListingsListingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$listingId': {
      id: '/listings/$listingId'
      path: '/listings/$listingId'
      fullPath: '/listings/$listingId'
      preLoaderRoute: typeof ListingsListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/staff': {
      id: '/dashboard/staff'
      path: '/dashboard/staff'
      fullPath: '/dashboard/staff'
      preLoaderRoute: typeof DashboardStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/seller': {
      id: '/dashboard/seller'
      path: '/dashboard/seller'
      fullPath: '/dashboard/seller'
      preLoaderRoute: typeof DashboardSellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/professional': {
      id: '/dashboard/professional'
      path: '/dashboard/professional'
      fullPath: '/dashboard/professional'
      preLoaderRoute: typeof DashboardProfessionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/buyer': {
      id: '/dashboard/buyer'
      path: '/dashboard/buyer'
      fullPath: '/dashboard/buyer'
      preLoaderRoute: typeof DashboardBuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/staff/': {
      id: '/dashboard/staff/'
      path: '/'
      fullPath: '/dashboard/staff/'
      preLoaderRoute: typeof DashboardStaffIndexRouteImport
      parentRoute: typeof DashboardStaffRoute
    }
    '/dashboard/seller/': {
      id: '/dashboard/seller/'
      path: '/'
      fullPath: '/dashboard/seller/'
      preLoaderRoute: typeof DashboardSellerIndexRouteImport
      parentRoute: typeof DashboardSellerRoute
    }
    '/dashboard/professional/': {
      id: '/dashboard/professional/'
      path: '/'
      fullPath: '/dashboard/professional/'
      preLoaderRoute: typeof DashboardProfessionalIndexRouteImport
      parentRoute: typeof DashboardProfessionalRoute
    }
    '/dashboard/buyer/': {
      id: '/dashboard/buyer/'
      path: '/'
      fullPath: '/dashboard/buyer/'
      preLoaderRoute: typeof DashboardBuyerIndexRouteImport
      parentRoute: typeof DashboardBuyerRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/staff/workflow': {
      id: '/dashboard/staff/workflow'
      path: '/workflow'
      fullPath: '/dashboard/staff/workflow'
      preLoaderRoute: typeof DashboardStaffWorkflowRouteImport
      parentRoute: typeof DashboardStaffRoute
    }
    '/dashboard/staff/submissions': {
      id: '/dashboard/staff/submissions'
      path: '/submissions'
      fullPath: '/dashboard/staff/submissions'
      preLoaderRoute: typeof DashboardStaffSubmissionsRouteImport
      parentRoute: typeof DashboardStaffRoute
    }
    '/dashboard/staff/credentials': {
      id: '/dashboard/staff/credentials'
      path: '/credentials'
      fullPath: '/dashboard/staff/credentials'
      preLoaderRoute: typeof DashboardStaffCredentialsRouteImport
      parentRoute: typeof DashboardStaffRoute
    }
    '/dashboard/seller/listings': {
      id: '/dashboard/seller/listings'
      path: '/listings'
      fullPath: '/dashboard/seller/listings'
      preLoaderRoute: typeof DashboardSellerListingsRouteImport
      parentRoute: typeof DashboardSellerRoute
    }
    '/dashboard/seller/documents': {
      id: '/dashboard/seller/documents'
      path: '/documents'
      fullPath: '/dashboard/seller/documents'
      preLoaderRoute: typeof DashboardSellerDocumentsRouteImport
      parentRoute: typeof DashboardSellerRoute
    }
    '/dashboard/professional/tasks': {
      id: '/dashboard/professional/tasks'
      path: '/tasks'
      fullPath: '/dashboard/professional/tasks'
      preLoaderRoute: typeof DashboardProfessionalTasksRouteImport
      parentRoute: typeof DashboardProfessionalRoute
    }
    '/dashboard/professional/credentials': {
      id: '/dashboard/professional/credentials'
      path: '/credentials'
      fullPath: '/dashboard/professional/credentials'
      preLoaderRoute: typeof DashboardProfessionalCredentialsRouteImport
      parentRoute: typeof DashboardProfessionalRoute
    }
    '/dashboard/buyer/transactions': {
      id: '/dashboard/buyer/transactions'
      path: '/transactions'
      fullPath: '/dashboard/buyer/transactions'
      preLoaderRoute: typeof DashboardBuyerTransactionsRouteImport
      parentRoute: typeof DashboardBuyerRoute
    }
    '/dashboard/buyer/services': {
      id: '/dashboard/buyer/services'
      path: '/services'
      fullPath: '/dashboard/buyer/services'
      preLoaderRoute: typeof DashboardBuyerServicesRouteImport
      parentRoute: typeof DashboardBuyerRoute
    }
    '/dashboard/buyer/listings': {
      id: '/dashboard/buyer/listings'
      path: '/listings'
      fullPath: '/dashboard/buyer/listings'
      preLoaderRoute: typeof DashboardBuyerListingsRouteImport
      parentRoute: typeof DashboardBuyerRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/settings': {
      id: '/dashboard/admin/settings'
      path: '/settings'
      fullPath: '/dashboard/admin/settings'
      preLoaderRoute: typeof DashboardAdminSettingsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/listings': {
      id: '/dashboard/admin/listings'
      path: '/listings'
      fullPath: '/dashboard/admin/listings'
      preLoaderRoute: typeof DashboardAdminListingsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/professional/tasks/$taskId': {
      id: '/dashboard/professional/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/dashboard/professional/tasks/$taskId'
      preLoaderRoute: typeof DashboardProfessionalTasksTaskIdRouteImport
      parentRoute: typeof DashboardProfessionalTasksRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminListingsRoute: typeof DashboardAdminListingsRoute
  DashboardAdminSettingsRoute: typeof DashboardAdminSettingsRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminListingsRoute: DashboardAdminListingsRoute,
  DashboardAdminSettingsRoute: DashboardAdminSettingsRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardBuyerRouteChildren {
  DashboardBuyerListingsRoute: typeof DashboardBuyerListingsRoute
  DashboardBuyerServicesRoute: typeof DashboardBuyerServicesRoute
  DashboardBuyerTransactionsRoute: typeof DashboardBuyerTransactionsRoute
  DashboardBuyerIndexRoute: typeof DashboardBuyerIndexRoute
}

const DashboardBuyerRouteChildren: DashboardBuyerRouteChildren = {
  DashboardBuyerListingsRoute: DashboardBuyerListingsRoute,
  DashboardBuyerServicesRoute: DashboardBuyerServicesRoute,
  DashboardBuyerTransactionsRoute: DashboardBuyerTransactionsRoute,
  DashboardBuyerIndexRoute: DashboardBuyerIndexRoute,
}

const DashboardBuyerRouteWithChildren = DashboardBuyerRoute._addFileChildren(
  DashboardBuyerRouteChildren,
)

interface DashboardProfessionalTasksRouteChildren {
  DashboardProfessionalTasksTaskIdRoute: typeof DashboardProfessionalTasksTaskIdRoute
}

const DashboardProfessionalTasksRouteChildren: DashboardProfessionalTasksRouteChildren =
  {
    DashboardProfessionalTasksTaskIdRoute:
      DashboardProfessionalTasksTaskIdRoute,
  }

const DashboardProfessionalTasksRouteWithChildren =
  DashboardProfessionalTasksRoute._addFileChildren(
    DashboardProfessionalTasksRouteChildren,
  )

interface DashboardProfessionalRouteChildren {
  DashboardProfessionalCredentialsRoute: typeof DashboardProfessionalCredentialsRoute
  DashboardProfessionalTasksRoute: typeof DashboardProfessionalTasksRouteWithChildren
  DashboardProfessionalIndexRoute: typeof DashboardProfessionalIndexRoute
}

const DashboardProfessionalRouteChildren: DashboardProfessionalRouteChildren = {
  DashboardProfessionalCredentialsRoute: DashboardProfessionalCredentialsRoute,
  DashboardProfessionalTasksRoute: DashboardProfessionalTasksRouteWithChildren,
  DashboardProfessionalIndexRoute: DashboardProfessionalIndexRoute,
}

const DashboardProfessionalRouteWithChildren =
  DashboardProfessionalRoute._addFileChildren(
    DashboardProfessionalRouteChildren,
  )

interface DashboardSellerRouteChildren {
  DashboardSellerDocumentsRoute: typeof DashboardSellerDocumentsRoute
  DashboardSellerListingsRoute: typeof DashboardSellerListingsRoute
  DashboardSellerIndexRoute: typeof DashboardSellerIndexRoute
}

const DashboardSellerRouteChildren: DashboardSellerRouteChildren = {
  DashboardSellerDocumentsRoute: DashboardSellerDocumentsRoute,
  DashboardSellerListingsRoute: DashboardSellerListingsRoute,
  DashboardSellerIndexRoute: DashboardSellerIndexRoute,
}

const DashboardSellerRouteWithChildren = DashboardSellerRoute._addFileChildren(
  DashboardSellerRouteChildren,
)

interface DashboardStaffRouteChildren {
  DashboardStaffCredentialsRoute: typeof DashboardStaffCredentialsRoute
  DashboardStaffSubmissionsRoute: typeof DashboardStaffSubmissionsRoute
  DashboardStaffWorkflowRoute: typeof DashboardStaffWorkflowRoute
  DashboardStaffIndexRoute: typeof DashboardStaffIndexRoute
}

const DashboardStaffRouteChildren: DashboardStaffRouteChildren = {
  DashboardStaffCredentialsRoute: DashboardStaffCredentialsRoute,
  DashboardStaffSubmissionsRoute: DashboardStaffSubmissionsRoute,
  DashboardStaffWorkflowRoute: DashboardStaffWorkflowRoute,
  DashboardStaffIndexRoute: DashboardStaffIndexRoute,
}

const DashboardStaffRouteWithChildren = DashboardStaffRoute._addFileChildren(
  DashboardStaffRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardBuyerRoute: DashboardBuyerRouteWithChildren,
  DashboardProfessionalRoute: DashboardProfessionalRouteWithChildren,
  DashboardSellerRoute: DashboardSellerRouteWithChildren,
  DashboardStaffRoute: DashboardStaffRouteWithChildren,
  ListingsListingIdRoute: ListingsListingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
